add contact form
riskmaris/mobile-App pull request #3
Opened 2023-06-05 10:37 UTC by riskmaris

2023-06-05 13:31 UTC, ShadyShawkat requested changes
## Hi @riskmaris, 

Good job so far! 👍🏻 
There are some issues that you still need to work on to go to the next project but you are almost there!

## To Highlight
- All linters are passing ✔️ 
- Descriptive commit messages ✔️ 
- Professional looking pull request ✔️ 

![Image](https://media.giphy.com/media/UdaSUYClr92cjWpeVx/giphy.gif)

## Required Changes ♻️
_Check the comments under the review._

## Optional suggestions
_Every comment with the [OPTIONAL] prefix is not crucial enough to stop the approval of this PR. However, I strongly recommend you to take them into account as they can make your code better._

Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
Please, remember to tag me in your question so I can receive the notification.

**_Please, do not open a new Pull Request for re-reviews. You should use the same Pull Request submitted for the first review, either valid or invalid unless it is requested otherwise._**

------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561) you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._

2023-06-05 15:10 UTC, riskmaris commented on index.html
>            </div>
Hi @ShadyShawkat 
I really don't understand what you mean because this is how the Figma design looks. Thanks

2023-06-05 15:13 UTC, ShadyShawkat commented on index.html
>            </div>
@riskmaris, I apologize, I should've been more precise with my feedback. I don't mean the inner spacing around the form. I meant the excess white space to the left and right of the design.

2023-06-05 17:03 UTC, Bantealem requested changes
Status; Required changes
Hi @riskmaris 

Great work on making the changes requested by a previous reviewer 👏 
You've done well implementing some of the requested changes, but there are still some which aren't addressed yet.


 ## Highlights
- [x] Correct GitHub flow
- [x] No Linters error
- [x] Professional README
- [x] Descriptive PR summary and title. 

 ## Required Changes ♻️
Please make sure your design is the same as Figma's design
Your design
![Screenshot from 2023-06-05 19-47-39](https://github.com/riskmaris/mobile-App/assets/101523582/93e14f75-91fe-4a71-8d54-500b795161ca)
Figma design
![image](https://github.com/riskmaris/mobile-App/assets/101523582/a67ddbfb-80a5-4e4d-a193-6409c72076a3)

_Check the comments under the review._

## Optional suggestions

_Every comment with the [OPTIONAL] prefix won't stop the approval of this PR. However, I strongly recommend you to take them into account as they can make your code better. Some of them were simply missed by the previous reviewer and addressing them will really improve your application._


Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
Please, remember to tag me in your question so I can receive the notification.

**_Please, do not open a new Pull Request for re-reviews. You should use the same Pull Request submitted for the first review, either valid or invalid unless it is requested otherwise._**


------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561)  you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._

2023-06-06 08:01 UTC, topeogunleye approved these changes
### Hi @riskmaris, 

# Status: Approved ✔️
Excellent job on making the changes requested by the previous code reviewer. Keep it up 👏

Your project is complete! There is nothing else to say other than... it's time to merge it 💪
Congratulations! 🎉
![congratulations](https://user-images.githubusercontent.com/52934128/163691476-087b4b9c-825b-40a3-85a1-d1bde44ffa53.gif)
>
## To highlight :champagne: 
- All linters are passing :heavy_check_mark: 
- Good commit history :heavy_check_mark: 
- Remove the excess spacing to the sides of the design  as suggested ✔️ 
- Use the same Font-color and font weight` as Figma design

## [Optional] suggestions:
* For future pull requests, please notice that your branch name mobile-app-potfolio does not follow the convention of being named after a feature or action. For example, you could name your branch `feature/addedMobileAppPotfolio`. This makes it easier to track the changes and the purpose of each branch.
 
 _Every comment with the [OPTIONAL] prefix is not crucial enough to stop the approval of this PR. However, I strongly recommend you to take them into account as they can make your code better._
 
Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
Please, remember to tag @topeogunleye in your question so I can receive the notification.



------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561)  you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._

2023-06-06 08:09 UTC, merged