Add desktop images and desktop styling
riskmaris/mobile-App pull request #4
Opened 2023-06-06 12:41 UTC by riskmaris

This is my Desktop Version milestone.

1. Added desktop images
2. Added a media query for desktop
3. Updated my README file

2023-06-06 13:53 UTC, Gambit142 requested changes
Hi @riskmaris 👋, 

Good job so far!

## Highlights
- All linters checks passed ✔️ 
- Used media queries for desktop screen ✔️ 
- Desktop version is responsive ✔️ 

You still need to work on some issues to go to the next project, but you are almost there!

## Required Changes ♻️
- [ ] _Kindly check the comments under the review._

## Optional suggestions
_Every comment with the [OPTIONAL] prefix is not crucial enough to stop the approval of this PR. However, I strongly recommend you consider them as they can improve your code._

You can also consider the following:

- [ ] _Kindly check the comments under the review tagged [OPTIONAL]._

Cheers, and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.

#### Please tag me in your question so I can receive the notification. You can tag me by typing @Gambit142

**_Please, do not open a new Pull Request for re-reviews. You should use the same Pull Request submitted for the first review, either valid or invalid unless it is requested otherwise._**

------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561) you have a limited number of reviews per project (check the exact number in your Dashboard). If you think the code review was unfair, request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._
```

2023-06-06 13:53 UTC, Gambit142 commented on README.md
>  <p align="right">(<a href="#readme-top">back to top</a>)</p>
- [ ] The link to your MIT LICENSE is broken and displayed an error page. Kindly fix it. 👍 

![image](https://github.com/riskmaris/mobile-App/assets/77106962/ee6de559-6344-4dcb-a010-569cc78d29fb)

2023-06-06 13:53 UTC, Gambit142 commented on style.css
> +  }
- [ ] The background of the headline section that has details of your name should be white all through but your design has some grey patches by the sides. I would advise you to increase the width to `100vw`. 👍 
- [ ] Also I would advise you to increase the `border-bottom-left-radius` to `9.4rem` so that your design can look identical to that of the Figma template that you chose. 👍 

| Your Design  | Figma Design |
| -------------- | --------------- |
| ![Screenshot_1](https://github.com/riskmaris/mobile-App/assets/77106962/939becfd-673e-41de-9654-087004d6cef5) | ![image](https://github.com/riskmaris/mobile-App/assets/77106962/9deea977-6f4d-4b2b-b44d-63b36068bd24)  |

2023-06-06 13:53 UTC, Gambit142 commented on index.html
> +                  </div>
- [ ] I noticed that you didn't adjust the font sizes of the headers for all the cards. The `font-size` should be `40px` or `2.5rem` with a `font-weight` of `700`. I think it would be nice if you implemented this suggestion so that your design looks identical to that of the Figma design for the desktop version. 👍 💻

2023-06-06 13:53 UTC, Gambit142 commented on index.html
> +            </header>
- [ ] I noticed that you didn't adjust the `font-size` of the header for the _**About-Me**_ section. The `font-size` should be `40px` or `2.5rem` with a `font-weight` of `700`. I think it would be nice if you implemented this suggestion so that your design looks identical to that of the Figma design for the desktop version. 👍 💻

2023-06-06 13:53 UTC, Gambit142 commented on style.css
> +  }
- [ ] Based on the Figma template design that you chose, the Languages sub-section of the About-Me section should occupy 60% of the space while the description part should occupy 40% of the space on the desktop version. In your design, they both occupy 50%. Kindly adjust the design to match that of the Figma template for this section. 💻 😎 

### Your Design

![image](https://github.com/riskmaris/mobile-App/assets/77106962/f90d04d2-1491-464b-a18b-89c50b9932d4)

### Figma template

![image](https://github.com/riskmaris/mobile-App/assets/77106962/d67ae00f-34b9-4d93-9424-baf5ef636601)

2023-06-06 13:53 UTC, Gambit142 commented on style.css
> +}
- [ ] Kindly implement the `hover`, `active`, `pressed` and `disabled` pseudo-classes interaction for the **_Get My Resume_** button. This will improve the UI for users and improve the aesthetic appeal. 

#### Hint: You can use the same style declarations that you used for other buttons when you implemented their interactions. 👍 😎

2023-06-06 13:53 UTC, Gambit142 commented on index.html
> +                <h2 class="contact">Contact Me</h2>
- [ ] I noticed that you didn't adjust the `font-size` of the header for the _**Contact/Form**_ section. The `font-size` should be `40px` or `2.5rem` with a `font-weight` of `700`. I think it would be nice if you implemented this suggestion so that your design looks identical to that of the Figma design for the desktop version. 👍 💻

2023-06-06 13:53 UTC, Gambit142 commented on index.html
> +              </div>
- [ ] The description section for the Contact/Form section has a `color` of `#EBEBFF` and a `font-size` of `1.25rem` on the desktop version. It would be nice if you implemented this suggestion so that your design looks identical to that of the Figma design for the desktop version. 👍 💻

2023-06-06 13:53 UTC, Gambit142 commented on style.css
> +}
- [OPTIONAL] I noticed that the mobile section is not fully responsive. It would be nice to fix this. 

![chrome-capture-2023-5-6](https://github.com/riskmaris/mobile-App/assets/77106962/a5cc60cd-5bb7-4a01-9bbe-53a9467a28c7)

2023-06-06 17:40 UTC, shahadat3669 requested changes
Hi @riskmaris , 

Great work on making the changes requested by a previous reviewer 👏 
You've done well implementing some of the requested changes, but there are still some which aren't addressed yet.

<img src="https://media2.giphy.com/media/m3864rBwwBTKMAbpn3/giphy.gif"/>

 ## Highlights
All linters checks passed ✔️
Used media queries for desktop screen ✔️
Desktop version is responsive ✔️

 ## Required Changes ♻️

_Check the comments under the review._

## Optional suggestions

Great job on creating a comprehensive and descriptive README file! 👍📚 I have a couple of suggestions to further improve the "Table of Contents" section:

- [Optional] Please update the links in your "Table of Contents" to ensure that they are working correctly. In the attached image, I have highlighted some links that appear to be broken. By fixing these links, you will ensure that readers can easily navigate to the respective sections.

- [Optional] Additionally, I noticed that there are some section headings listed in the "Table of Contents" that are not available in your README file. I have marked these headings in red in the image. To maintain consistency and avoid confusion, it would be best to remove these headings from the "Table of Contents" if the corresponding sections are not present in your README file.

![image](https://github.com/riskmaris/mobile-App/assets/55840999/b7ec1e50-f028-4509-86bb-1431d6630d07)


_Every comment with the [OPTIONAL] prefix won't stop the approval of this PR. However, I strongly recommend you to take them into account as they can make your code better. Some of them were simply missed by the previous reviewer and addressing them will really improve your application._


Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
Please, remember to tag me in your question so I can receive the notification.

**_Please, do not open a new Pull Request for re-reviews. You should use the same Pull Request submitted for the first review, either valid or invalid unless it is requested otherwise._**


------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561)  you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._

2023-06-06 17:40 UTC, shahadat3669 commented on index.html
> +                  </div>
Great work so far! 👏 There are a couple of improvements to be made for the headers in the cards to align with the design on the desktop version:

- [ ] Please update the font sizes of the headers in all the cards to be 40px or 2.5rem, as per the design specifications. This change will ensure consistency and make your design closely resemble the Figma design for the desktop version. 👍💻
- [ ] [Optional] It appears that you're using the `<h1>` tag for the card titles. However, it's recommended to have only one `<h1>` tag per webpage for better accessibility. And in the heading of this webpage, you already have one H1 title. So consider replacing the `<h1>` tag with an appropriate heading tag, such as `<h2>` to `<h6>`, depending on the hierarchy and relevance of the titles within your code. You can refer to the [documentation on heading elements](https://developer.mozilla.org/en-US/docs/Web/HTML/Element/Heading_Elements#accessibility_concerns) for more information.

By implementing these suggestions, you'll ensure that your design is consistent and adheres to best practices. Keep up the excellent work!

2023-06-06 17:40 UTC, shahadat3669 commented on index.html
> +            </header>
Great job! 👏 As mentioned by the previous reviewer, there are a couple of adjustments needed for the header in the About-Me section to match the design on the desktop version:

- [ ] Please update the font size of the header to be 40px or 2.5rem, as per the design specifications. This change will ensure that your design closely resembles the Figma design for the desktop version. 👍💻
- [ ] [Optional] It seems that the title color doesn't match the design. Please consider adjusting the color to match the specified design.

By implementing these suggestions, you will achieve greater consistency and ensure that your design aligns with the intended specifications. Keep up the great work!

2023-06-06 17:40 UTC, shahadat3669 commented on index.html
> +            <button class="resume"><a href="#">Get my resume</a></button>
👋 Hello! Congratulations on your progress so far! I have a couple of suggestions to further enhance the "Get My Resume" button in line with the design:

- [ ] As mentioned by the previous reviewer, please add styles for the active, hover, pressed, and disabled states of the "Get My Resume" button as per design. These states are crucial for providing visual feedback and ensuring a consistent user experience. Implementing these styles will help the button align with the design specifications and improve its overall appearance. 👍🎨

![image](https://github.com/riskmaris/mobile-App/assets/55840999/89e57458-b950-46b3-8613-ec442c3b03b2)

- [ Optional] Additionally, currently your button text is wrapped by the "<a>" tag and the button wraps the "<a>" tag. It is not necessary. you might consider using either the `<button>` or `<a>` tag for the "Get My Resume" button, based on your specific needs. Choose the element that best aligns with the purpose and functionality of the button in your project.

By implementing these suggestions, you'll ensure that the button behaves as intended, matches the design specifications, and contributes to the overall professionalism and polish of your project. Keep up the great work!

2023-06-06 17:40 UTC, shahadat3669 commented on index.html
> +                <h2 class="contact">Contact Me</h2>
👋 Hello! Congratulations on your work so far! I have a suggestion to further align your Contact/Form section with the design:

- [ ] As mentioned by the previous reviewer, please update the font size to 40px or 2.5rem. This will ensure that your design matches the Figma design for the desktop version and maintains consistency. 💻👍

By implementing this suggestion, your Contact/Form section will have a visually appealing and cohesive look, enhancing the overall user experience. Keep up the great work!

2023-06-06 17:40 UTC, shahadat3669 commented on index.html
> +              </div>
👋 Hello! Great work on the form! I have a small suggestion to align with the design requirements:

- [ ] As the previous reviewer mentioned, please add the correct color and font size for the form description. This will help ensure consistency and adhere to the design specifications. 🎨

By making this adjustment, your form will be even more visually appealing and in line with the intended design. Keep up the good work! 👍

2023-06-07 07:56 UTC, Shisui6 approved these changes
Hi @riskmaris, 

# Approved 🪄
Your project is complete! There is nothing else to say other than... it's time to merge it 💎
Congratulations! 🎉 

## Highlights 🎯
- Good use of media queries ✅
- Good design ✅


## Optional suggestions 🪶

_Every comment with the [OPTIONAL] prefix won't stop the approval of this PR. However, I strongly recommend you consider them as they can improve your code. Some of them were simply missed by the previous reviewer, and addressing them will really improve your application._

You can also consider the following:

N/A

Cheers and Happy coding!🍻💻

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
Please, remember to tag me in your question so I can receive the notification.

------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561), you have a limited number of reviews per project (check the exact number in your Dashboard). If you think the code review was unfair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._

2023-06-07 13:23 UTC, merged