Add popup details on main.js file
riskmaris/mobile-App pull request #8
Opened 2023-06-21 09:30 UTC by riskmaris

For this milestone:

1. Used JavaScript to manipulate DOM elements.
2. Used JavaScript events.

2023-06-21 13:04 UTC, Shisui6 reviewed
Hi @riskmaris, 

While you made a great effort in this project, unfortunately, I cannot proceed to review your code.

## Invalid Code Review Request 🛠️

You have submitted a javascript project that that doesn't have the eslint linter checks setup. Please add the javascript linters to your project.

Your Code Review Request will be marked as invalid in your Dashboard, so please submit a new one once you are ready 🙏

Cheers and Happy coding!🍻💻

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
Please, remember to tag me in your question so I can receive the notification.

**_Please, do not open a new Pull Request for re-reviews. You should use the same Pull Request submitted for the first review, either valid or invalid, unless it is requested otherwise._**

--------

_Invalid Code Review Request **does not count** into the code reviews limit._

2023-06-21 14:44 UTC, tugsem requested changes
##  STATUS: REQUIRED CHANGES ♻️
Hello @Porkalaikarthika and @riskmaris 👋 , 

Good job so far! 👏 
There are some issues that you still need to work on to go to the next project but you are almost there!

![ Alt Text](https://media.giphy.com/media/l0MYC5rnAHehkVKRq/giphy.gif)
## Highlights 🚀 
✔️work created dynamically
✔️close and open buttons work as expected
✔️styling for both mobile and desktop looks pretty much like the figma design.
## Required Changes ♻️
_Check the comments under the review._

## Optional suggestions
_Every comment with the [OPTIONAL] prefix is not crucial enough to stop the approval of this PR. However, I strongly recommend you to take them into account as they can make your code better._

Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
Please, remember to tag me in your question so I can receive the notification.

**_Please, do not open a new Pull Request for re-reviews. You should use the same Pull Request submitted for the first review, either valid or invalid unless it is requested otherwise._**

------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561) you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._

2023-06-21 14:44 UTC, tugsem commented on style.css
> +}
- [ ] Kindly give more spacing around these elements to match the given design: 
>yours:
![image](https://github.com/riskmaris/mobile-App/assets/91486791/0b24ca7d-040a-4e16-a393-2413213fc8a9)
> figma:
![image](https://github.com/riskmaris/mobile-App/assets/91486791/f90bbb88-a817-4216-a88b-91ce061adcf2)

2023-06-21 14:44 UTC, tugsem commented on style.css
> +}
- [ ] Kindly decrease the space between these buttons to match the figma design. Also please add the light colored line dividing these technologies and buttons: 
> yours:
![image](https://github.com/riskmaris/mobile-App/assets/91486791/6d36ebdf-2206-410d-a6a2-aa53dd9a519e)
>figma:
![image](https://github.com/riskmaris/mobile-App/assets/91486791/1213a59c-b6ad-4a2d-8141-cf85b528a536)

2023-06-21 14:44 UTC, tugsem commented on style.css
> +}
- [ ] Kindly make your image to fit perfectly in the container here for mobile screens to match the figma design. Also, in smaller screens like 375px, which we should also consider to be responsive, image overlaps its container. I will attach the image below:
>yours: 
![image](https://github.com/riskmaris/mobile-App/assets/91486791/7e94e025-81fb-4cfd-aad8-a72518c54c96)
![image](https://github.com/riskmaris/mobile-App/assets/91486791/e6bbf4d0-01cb-48c6-aecc-902945a8b1d0)
>figma:
![image](https://github.com/riskmaris/mobile-App/assets/91486791/2e543a81-6a37-471d-a131-40fae96fafc6)

2023-06-21 14:44 UTC, tugsem commented on main.js
> +}
- [ ] Kindly remove scrolling from your body element when the popup menu appears. This will match the figma design and look more professional. Here's the video link: https://clipchamp.com/watch/PGGbSHzBhmb

2023-06-21 14:44 UTC, tugsem commented on style.css
> +}
- [ ] To match the design outlines, kindly make your buttons below to not wrap the content on a new line when the width get smaller. Also, there should be more space between them, right now, they are sticking to each other and icons get on the bottom line:
>yours:
![image](https://github.com/riskmaris/mobile-App/assets/91486791/b6742387-89d3-4d02-8b09-87472101fa0f)
>figma:
![image](https://github.com/riskmaris/mobile-App/assets/91486791/422533d0-c919-40c5-8f06-0be35f48b122)

2023-06-21 17:50 UTC, riskmaris commented
The popup window is really challenging. And I tried all I could to make the changes.
Please help me where necessary. I really hope that I pass this time. Thank you

2023-06-21 19:24 UTC, GzimAsani requested changes
### Hello, @riskmaris                         :wave:   
 Good job so far,  done There are some issues that you still need to work on to go to the next project but you are almost there!
 
 ## Highlights
 * Good job with the design of popup  +1: 

 ## Required Changes 

- [ ] Check for the comments below :arrow_double_down: 

 ## Optional suggestions
 _Every comment with the [OPTIONAL] prefix is not crucial enough to stop the approval of this PR. However, I strongly recommend you to take them into account as they can make your code better._

- N/A



Cheers and Happy coding! clapclapclap
 
 Feel free to leave any questions or comments in the PR thread if something is not 100% clear. Please, remember to tag me in your question so I can receive the notification.
 
 **_Please, do not open a new Pull Request for re-reviews. You should use the same Pull Request submitted for the first review, either valid or invalid unless it is requested otherwise._**
 
 _As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561) you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._

2023-06-21 19:24 UTC, GzimAsani commented on index.html
>          <header class="navbar">
- [ OPTIONAL ] As mentioned by the previous reviewer the navbar is not showing on desktop, kindly fix it
![image](https://github.com/riskmaris/mobile-App/assets/62705947/d7d53c22-7297-44ea-8a1d-10d5d640aa99)

2023-06-21 19:24 UTC, GzimAsani commented on index.html
>          <header class="navbar">
- [ ] As mentioned by the previous reviewer kindly make sure that the page is not scroll-able when the popup is open.
- [ OPTIONAL ] I would add this as optional because it wasn't required by the previous reviewer but it is important to match the design: Based on the design the background needs to also be blur when the popup is open. 
![image](https://github.com/riskmaris/mobile-App/assets/62705947/804bed3a-dc5a-47c6-bf17-3469b84f01f8)

2023-06-22 08:14 UTC, riskmaris commented
This is my last chance to submit please, and I really hope that I pass so that I can go to the next project please.
Thank you for your help

2023-06-22 08:33 UTC, wayungi approved these changes
Hi @riskmaris , 

![image](https://user-images.githubusercontent.com/99656687/220082459-c1b049c7-5498-42e7-942b-ec7a05d3e603.png)

Great work, your project is complete!  There is nothing else to say other than... it's time to merge it :shipit: 
Congratulations! 🎉 

**Remember: Every finish line 🏁  is the beginning of a new race 🐎** 

## Highlights
- [ ] Well written README ✔️ 
- [ ]  Correct GitHub flow ✔️ 
- [ ] Project up and running ✔️ 

## Optional suggestions

- [ ]  Please make sure the image in the mobile pop up is correctly aligned as in the figma
![tonic](https://github.com/riskmaris/mobile-App/assets/99656687/602bc797-ad99-4cac-b583-0852cc2fed2d)
 
_Every comment with the [OPTIONAL] prefix won't stop the approval of this PR. However, I strongly recommend you to take them into account as they can make your code better. Some of them were simply missed by the previous reviewer and addressing them will really improve your application._

Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
Please, remember to tag me in your question so I can receive the notification.

------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561)  you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._

2023-06-22 09:18 UTC, merged